#!/usr/bin/env python3
"""Generate exact FP product and add-product RTL oracle vectors.

The expected results come directly from the shared exact IEEE reference
(shared/ieee_fp.py).
Each row exercises both the product-only binary32 result used by WMUL and the
single-round ``binary32 accumulator + exact FP16/BF16 product`` operation used
by TAMAC.

Regenerate from the repository root with:

    python3 rtl/sim/gen_fp_exact_vectors.py > rtl/sim/fp_exact_vectors.vec
"""

from __future__ import annotations

from pathlib import Path
import random
import sys


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from shared import ieee_fp  # noqa: E402

EW_FP16 = ieee_fp.FP16.ew
EW_BF16 = ieee_fp.BF16.ew


def _product_to_fp32(a_raw: int, b_raw: int, ew: int) -> int:
    """WMUL: the exact product rounded once to binary32."""
    return ieee_fp.product(
        ieee_fp.FP32, ieee_fp.FORMAT_BY_EW[ew], a_raw, b_raw
    )[0]


def _add_product_to_fp32(acc: int, a_raw: int, b_raw: int, ew: int) -> int:
    """TAMAC: binary32 accumulator plus exact product, rounded once."""
    return ieee_fp.mixed_fma(
        ieee_fp.FP32, ieee_fp.FORMAT_BY_EW[ew], a_raw, b_raw, acc
    )[0]


# Named vectors pin the boundaries that are easiest to implement incorrectly.
# The random tail then covers ordinary normalization/alignment combinations
# without making the Verilog testbench an independent arithmetic oracle.
NAMED_CASES = (
    ("fp16_basic", EW_FP16, 0x3C00, 0x4000, 0x0000_0000),
    ("fp16_exact_extra_bits", EW_FP16, 0x3C01, 0x3C01, 0x0000_0000),
    ("fp16_smallest_subnormal", EW_FP16, 0x0001, 0x3C00, 0x0000_0000),
    ("fp16_negative_underflow", EW_FP16, 0x8001, 0x0001, 0x0000_0000),
    ("fp16_zero_times_inf", EW_FP16, 0x0000, 0x7C00, 0x0000_0000),
    ("fp16_nan_payload", EW_FP16, 0x7E55, 0x3C00, 0x0000_0000),
    ("fp16_opposite_infinities", EW_FP16, 0xFC00, 0x3C00, 0x7F80_0000),
    ("fp16_exact_cancel", EW_FP16, 0xBC00, 0x3C00, 0x3F80_0000),
    ("fp16_negative_zero_pair", EW_FP16, 0x8000, 0x3C00, 0x8000_0000),
    ("bf16_tie_even_down", EW_BF16, 0x3980, 0x3980, 0x3F80_0000),
    ("bf16_tie_even_up", EW_BF16, 0x3980, 0x3980, 0x3F80_0001),
    ("bf16_product_half_subulp", EW_BF16, 0x0001, 0x3700, 0x0000_0001),
    ("bf16_subnormal_product", EW_BF16, 0x0001, 0x3F80, 0x0000_0000),
    ("bf16_overflow", EW_BF16, 0x7F7F, 0x4000, 0x0000_0000),
    ("bf16_negative_underflow", EW_BF16, 0x8001, 0x0001, 0x0000_0000),
    ("bf16_zero_times_inf", EW_BF16, 0x8000, 0x7F80, 0x0000_0000),
    ("bf16_acc_nan", EW_BF16, 0x3F80, 0x3F80, 0xFFC1_2345),
)


def _random_cases() -> list[tuple[str, int, int, int, int]]:
    rng = random.Random(0x5441_4343)
    rows: list[tuple[str, int, int, int, int]] = []
    fp32_edges = (
        0x0000_0000,
        0x8000_0000,
        0x0000_0001,
        0x007F_FFFF,
        0x0080_0000,
        0x3F7F_FFFF,
        0x3F80_0000,
        0x3F80_0001,
        0x7F7F_FFFF,
        0x7F80_0000,
        0xFF80_0000,
        0x7FC0_0001,
    )
    for ew, label in ((EW_FP16, "fp16"), (EW_BF16, "bf16")):
        for index in range(96):
            a = rng.getrandbits(16)
            b = rng.getrandbits(16)
            acc = (
                fp32_edges[index % len(fp32_edges)]
                if index < len(fp32_edges) * 2
                else rng.getrandbits(32)
            )
            rows.append((f"{label}_random_{index:02d}", ew, a, b, acc))
    return rows


def main() -> None:
    print("# Generated by rtl/sim/gen_fp_exact_vectors.py; do not edit.")
    print("# name is_bf16 a b acc expected_product expected_add_product")
    for name, ew, a, b, acc in (*NAMED_CASES, *_random_cases()):
        product = _product_to_fp32(a, b, ew)
        feedback = _add_product_to_fp32(acc, a, b, ew)
        print(
            f"{name} {int(ew == EW_BF16)} {a:04x} {b:04x} "
            f"{acc:08x} {product:08x} {feedback:08x}"
        )


if __name__ == "__main__":
    main()
