`timescale 1ns/1ps

// ============================================================================
// Exact FP16/BF16 product and binary32 feedback regression
// ============================================================================
//
// Expected values are generated by the Phase-1 integer IEEE oracle.  This
// bench deliberately does not reproduce the arithmetic in SystemVerilog.

module tb_fp_exact;
    reg         is_bf16;
    reg  [15:0] operand_a;
    reg  [15:0] operand_b;
    reg  [31:0] accumulator;

    wire        product_nan;
    wire        product_inf;
    wire        product_zero;
    wire        product_finite;
    wire        product_sign;
    wire [21:0] product_significand;
    wire signed [10:0] product_exponent;
    wire [31:0] rounded_product;
    wire [31:0] add_product_result;

    reg  [31:0] add_a;
    reg  [31:0] add_b;
    wire [31:0] add_result;

    integer vector_fd;
    integer vector_scan;
    integer vector_count;
    integer pass_count;
    integer fail_count;
    reg [2047:0] vector_line;
    reg [767:0]  vector_name;
    integer      vector_is_bf16;
    reg [15:0]   vector_a;
    reg [15:0]   vector_b;
    reg [31:0]   vector_acc;
    reg [31:0]   vector_product;
    reg [31:0]   vector_feedback;

    mp64_fp16_bf16_exact_product u_product (
        .is_bf16           (is_bf16),
        .a                  (operand_a),
        .b                  (operand_b),
        .product_nan        (product_nan),
        .product_inf        (product_inf),
        .product_zero       (product_zero),
        .product_finite     (product_finite),
        .product_sign       (product_sign),
        .product_significand(product_significand),
        .product_exponent   (product_exponent),
        .rounded_fp32       (rounded_product)
    );

    mp64_fp32_add_exact_product_rne u_add_product (
        .accumulator        (accumulator),
        .product_nan        (product_nan),
        .product_inf        (product_inf),
        .product_zero       (product_zero),
        .product_finite     (product_finite),
        .product_sign       (product_sign),
        .product_significand(product_significand),
        .product_exponent   (product_exponent),
        .result             (add_product_result)
    );

    mp64_fp32_add_rne u_add (
        .a     (add_a),
        .b     (add_b),
        .result(add_result)
    );

    task check;
        input [767:0] label;
        input         condition;
    begin
        if (condition) begin
            pass_count = pass_count + 1;
        end else begin
            fail_count = fail_count + 1;
            $display("  FAIL: %0s", label);
        end
    end
    endtask

    task check_add;
        input [767:0] label;
        input [31:0]  lhs;
        input [31:0]  rhs;
        input [31:0]  expected;
    begin
        add_a = lhs;
        add_b = rhs;
        #1;
        if (add_result == expected) begin
            pass_count = pass_count + 1;
        end else begin
            fail_count = fail_count + 1;
            $display(
                "  FAIL: %0s: %08x + %08x = %08x, expected %08x",
                label, lhs, rhs, add_result, expected);
        end
    end
    endtask

    initial begin
        pass_count = 0;
        fail_count = 0;
        vector_count = 0;
        is_bf16 = 1'b0;
        operand_a = 16'd0;
        operand_b = 16'd0;
        accumulator = 32'd0;
        add_a = 32'd0;
        add_b = 32'd0;

        vector_fd = $fopen("fp_exact_vectors.vec", "r");
        if (vector_fd == 0)
            $fatal(1, "cannot open fp_exact_vectors.vec");

        while (!$feof(vector_fd)) begin
            vector_line = {2048{1'b0}};
            vector_scan = $fgets(vector_line, vector_fd);
            vector_scan = $sscanf(
                vector_line,
                "%s %d %h %h %h %h %h",
                vector_name,
                vector_is_bf16,
                vector_a,
                vector_b,
                vector_acc,
                vector_product,
                vector_feedback);
            if (vector_scan == 7) begin
                vector_count = vector_count + 1;
                is_bf16 = vector_is_bf16[0];
                operand_a = vector_a;
                operand_b = vector_b;
                accumulator = vector_acc;
                #1;

                if (rounded_product != vector_product) begin
                    fail_count = fail_count + 1;
                    $display(
                        "  FAIL: %0s product %08x, expected %08x",
                        vector_name, rounded_product, vector_product);
                end else begin
                    pass_count = pass_count + 1;
                end

                if (add_product_result != vector_feedback) begin
                    fail_count = fail_count + 1;
                    $display(
                        "  FAIL: %0s feedback %08x, expected %08x",
                        vector_name, add_product_result, vector_feedback);
                end else begin
                    pass_count = pass_count + 1;
                end

                check(
                    "product descriptor class is one-hot",
                    product_nan + product_inf +
                    product_zero + product_finite == 1);
            end
        end
        $fclose(vector_fd);

        check("all generated vectors executed", vector_count == 209);

        // Descriptor checks prove that the exact product, rather than its
        // rounded binary32 view, remains available to the feedback bank.
        is_bf16 = 1'b0;
        operand_a = 16'h3C01;
        operand_b = 16'h3C01;
        #1;
        check("FP16 descriptor retains the full 11x11 product",
              product_finite &&
              product_significand == 22'd1050625 &&
              product_exponent == -11'sd20);

        is_bf16 = 1'b1;
        operand_a = 16'h0001;
        operand_b = 16'h3700;
        #1;
        check("BF16 descriptor retains a half-subnormal-ULP product",
              product_finite &&
              product_significand == 22'd128 &&
              product_exponent == -11'sd157);

        // Direct binary32 addition uses the same canonical special-value and
        // final-rounding core as add-product feedback.
        check_add("ordinary one plus one",
                  32'h3F80_0000, 32'h3F80_0000, 32'h4000_0000);
        check_add("minimum subnormal addition",
                  32'h0000_0001, 32'h0000_0001, 32'h0000_0002);
        check_add("largest subnormal rounds into minimum normal",
                  32'h007F_FFFF, 32'h0000_0001, 32'h0080_0000);
        check_add("tie-even retains even significand",
                  32'h3F80_0000, 32'h3380_0000, 32'h3F80_0000);
        check_add("tie-even advances odd significand",
                  32'h3F80_0001, 32'h3380_0000, 32'h3F80_0002);
        check_add("exact cancellation produces positive zero",
                  32'h3F80_0000, 32'hBF80_0000, 32'h0000_0000);
        check_add("two negative zeroes produce negative zero",
                  32'h8000_0000, 32'h8000_0000, 32'h8000_0000);
        check_add("mixed signed zeroes produce positive zero",
                  32'h0000_0000, 32'h8000_0000, 32'h0000_0000);
        check_add("opposite infinities canonicalize NaN",
                  32'h7F80_0000, 32'hFF80_0000, 32'h7FC0_0000);
        check_add("NaN payload is canonicalized",
                  32'hFFC1_2345, 32'h3F80_0000, 32'h7FC0_0000);

        if (fail_count == 0) begin
            $display(
                "PASS: exact FP product/feedback (%0d checks)",
                pass_count);
            $finish;
        end

        $fatal(
            1,
            "exact FP product/feedback failed: %0d passed, %0d failed",
            pass_count,
            fail_count);
    end
endmodule
