// ============================================================================
// tb_tile_fp.v — tile golden vectors
// ============================================================================
//
// Replays rtl/sim/tile_fp_vectors.vec, generated by gen_tile_fp_vectors.py
// from the Python emulator and the shared exact reference
// (docs/floating-point.md).  Each record seeds TMODE, TCTRL, ACC0-3, the
// source and destination tiles, dispatches one MEX operation, and compares
// the destination tiles, accumulator words, TCTRL, and the completion's
// FLAGS.Z update selected by its check mask.
//

`timescale 1ns / 1ps
`include "mp64_pkg.vh"

module tb_tile_fp;

    reg clk, rst_n;
    initial clk = 0;
    always #5 clk = ~clk;

    // === CSR interface ===
    reg         csr_wen;
    reg  [7:0]  csr_addr;
    reg  [63:0] csr_wdata;
    wire [63:0] csr_rdata;

    // === MEX dispatch ===
    reg         mex_valid;
    reg  [1:0]  mex_ss;
    reg  [1:0]  mex_op;
    reg  [2:0]  mex_funct;
    reg  [7:0]  mex_funct_byte;
    reg  [63:0] mex_gpr_val;
    reg  [7:0]  mex_imm8;
    reg  [3:0]  mex_ext_mod;
    reg         mex_ext_active;
    reg  [4:0]  mex_caller_id;
    reg         mex_priv;
    reg  [63:0] mex_mpu_base;
    reg  [63:0] mex_mpu_limit;
    reg         mex_mpu_enabled;
    reg         mex_allow_cluster_spad;
    reg  [7:0]  mex_engine_epoch;
    reg  [7:0]  mex_caller_epoch;
    reg  [1:0]  mex_caller_slot;
    reg         engine_reset;
    reg  [3:0]  caller_cancel;
    reg  [31:0] caller_epochs;
    wire [7:0]  engine_epoch;
    wire        mex_done;
    wire        mex_zero_valid;
    wire        mex_zero;
    wire        mex_busy;
    wire [2:0]  mex_fault;
    wire [63:0] mex_fault_addr;
    wire        mex_stall_cycle;

    reg         tacc_ctl_valid;
    reg  [4:0]  tacc_ctl_caller_id;
    reg         tacc_ctl_priv;
    reg  [63:0] tacc_ctl_wdata;
    wire [63:0] tacc_status_raw;
    wire        tacc_ctl_done;
    wire [2:0]  tacc_ctl_fault;
    wire [255:0] legacy_acc_state;
    wire         acc_zero_consumed;

    // === Tile memory port — simple 1-cycle BRAM model ===
    wire        tile_req;
    wire [31:0] tile_addr;
    wire        tile_wen;
    wire [511:0] tile_wdata;
    reg  [511:0] tile_rdata;
    reg          tile_ack;
    reg          tile_ack_enable;

    // === External tile port (unused — stub) ===
    wire        ext_tile_req;
    wire [63:0] ext_tile_addr;
    wire        ext_tile_wen;
    wire [511:0] ext_tile_wdata;
    reg  [511:0] ext_tile_rdata;
    reg          ext_tile_ack;

    // Simple tile BRAM model (256 tiles × 512 bits = 16 KiB)
    reg [511:0] tile_mem [0:255];

    always @(posedge clk) begin
        tile_ack <= 1'b0;
        if (tile_req && tile_ack_enable) begin
            if (tile_wen)
                tile_mem[tile_addr[13:6]] <= tile_wdata;
            tile_rdata <= tile_mem[tile_addr[13:6]];
            tile_ack   <= 1'b1;
        end
    end

    // DUT
    mp64_tile u_tile (
        .clk           (clk),
        .rst_n         (rst_n),
        .engine_reset  (engine_reset),
        .caller_cancel (caller_cancel),
        .caller_epochs (caller_epochs),
        .engine_epoch  (engine_epoch),
        .mex_retire    (1'b1),
        .csr_wen       (csr_wen),
        .csr_addr      (csr_addr),
        .csr_wdata     (csr_wdata),
        .csr_rdata     (csr_rdata),
        .mex_valid     (mex_valid),
        .mex_ss        (mex_ss),
        .mex_op        (mex_op),
        .mex_funct     (mex_funct),
        .mex_funct_byte(mex_funct_byte),
        .mex_gpr_val   (mex_gpr_val),
        .mex_imm8      (mex_imm8),
        .mex_ext_mod   (mex_ext_mod),
        .mex_ext_active(mex_ext_active),
        .mex_caller_id (mex_caller_id),
        .mex_priv      (mex_priv),
        .mex_mpu_base  (mex_mpu_base),
        .mex_mpu_limit (mex_mpu_limit),
        .mex_mpu_enabled(mex_mpu_enabled),
        .mex_allow_cluster_spad(mex_allow_cluster_spad),
        .mex_engine_epoch(mex_engine_epoch),
        .mex_caller_epoch(mex_caller_epoch),
        .mex_caller_slot(mex_caller_slot),
        .mex_done      (mex_done),
        .mex_zero_valid(mex_zero_valid),
        .mex_zero      (mex_zero),
        .mex_busy      (mex_busy),
        .mex_fault     (mex_fault),
        .mex_fault_addr(mex_fault_addr),
        .mex_stall_cycle(mex_stall_cycle),
        .tacc_status_raw(tacc_status_raw),
        .tacc_ctl_valid(tacc_ctl_valid),
        .tacc_ctl_caller_id(tacc_ctl_caller_id),
        .tacc_ctl_priv (tacc_ctl_priv),
        .tacc_ctl_wdata(tacc_ctl_wdata),
        .tacc_ctl_done (tacc_ctl_done),
        .tacc_ctl_fault(tacc_ctl_fault),
        .legacy_acc_state(legacy_acc_state),
        .legacy_acc_wen(4'd0),
        .legacy_acc_wdata(256'd0),
        .cfg_load      (1'b0),
        .cfg_tmode     (64'd0),
        .cfg_tctrl     (64'd0),
        .cfg_tsrc0     (64'd0),
        .cfg_tsrc1     (64'd0),
        .cfg_tdst      (64'd0),
        .cfg_sb        (64'd0),
        .cfg_sr        (64'd0),
        .cfg_sc        (64'd0),
        .cfg_sw        (64'd0),
        .cfg_tstride_r (64'd0),
        .cfg_tstride_c (64'd0),
        .cfg_ttile_h   (64'd0),
        .cfg_ttile_w   (64'd0),
        .acc_zero_consumed(acc_zero_consumed),
        .tile_req      (tile_req),
        .tile_addr     (tile_addr),
        .tile_wen      (tile_wen),
        .tile_wdata    (tile_wdata),
        .tile_rdata    (tile_rdata),
        .tile_ack      (tile_ack),
        .tile_error    (1'b0),
        .tile_fault_addr(64'd0),
        .ext_tile_req  (ext_tile_req),
        .ext_tile_addr (ext_tile_addr),
        .ext_tile_wen  (ext_tile_wen),
        .ext_tile_wdata(ext_tile_wdata),
        .ext_tile_rdata(ext_tile_rdata),
        .ext_tile_ack  (ext_tile_ack),
        .ext_tile_error(1'b0),
        .ext_tile_fault_addr(64'd0),
        .tile_source_cancel()
    );

    integer pass_cnt, fail_cnt, vector_count, expected_count;
    integer fd, code;
    reg [8*2048-1:0] line;
    reg [8*64-1:0]   name;
    reg [3:0]   v_ss, v_op;
    reg [7:0]   v_funct_byte, v_tmode, v_tctrl, v_etctrl, v_check;
    reg [3:0]   v_ez_valid, v_ez;
    reg         seen_z_valid, seen_z;
    reg [63:0]  v_gpr;
    reg [63:0]  v_acc [0:3];
    reg [63:0]  v_eacc [0:3];
    reg [511:0] v_src0, v_src1, v_dst, v_dst2, v_edst, v_edst2;
    reg [63:0]  tctrl_now;
    integer k;
    reg ok;

    task csr_write;
        input [7:0]  addr;
        input [63:0] data;
    begin
        @(posedge clk);
        csr_wen   <= 1;
        csr_addr  <= addr;
        csr_wdata <= data;
        @(posedge clk);
        csr_wen <= 0;
    end
    endtask

    task csr_read;
        input  [7:0]  addr;
        output [63:0] data;
    begin
        @(posedge clk);
        csr_addr <= addr;
        @(posedge clk);
        data = csr_rdata;
    end
    endtask

    // The architectural immediate form forces function 0 and takes the
    // function byte as its immediate.
    task dispatch;
        input [1:0] ss;
        input [1:0] op;
        input [7:0] funct_byte;
        input [63:0] gpr;
    begin
        @(posedge clk);
        mex_valid      <= 1'b1;
        mex_ss         <= ss;
        mex_op         <= op;
        mex_funct      <= (ss == 2'd2) ? 3'd0 : funct_byte[2:0];
        mex_funct_byte <= funct_byte;
        mex_gpr_val    <= gpr;
        mex_imm8       <= (ss == 2'd2) ? funct_byte : 8'd0;
        mex_ext_mod    <= 4'd0;
        mex_ext_active <= 1'b0;
        @(posedge clk);
        mex_valid <= 1'b0;
        while (!mex_done) @(posedge clk);
        seen_z_valid = mex_zero_valid;
        seen_z       = mex_zero;
        @(posedge clk);
    end
    endtask

    initial begin
        pass_cnt = 0;
        fail_cnt = 0;
        vector_count = 0;
        expected_count = -1;
        rst_n = 0;
        csr_wen = 0; csr_addr = 0; csr_wdata = 0;
        mex_valid = 0; mex_ss = 0; mex_op = 0; mex_funct = 0;
        mex_funct_byte = 0; mex_gpr_val = 0; mex_imm8 = 0;
        mex_ext_mod = 0; mex_ext_active = 0;
        mex_caller_id = 5'd0; mex_priv = 1'b0;
        mex_mpu_base = 64'd0; mex_mpu_limit = 64'd0;
        mex_mpu_enabled = 1'b0; mex_allow_cluster_spad = 1'b0;
        mex_engine_epoch = 8'd0; mex_caller_epoch = 8'd0;
        mex_caller_slot = 2'd0; engine_reset = 1'b0;
        caller_cancel = 4'd0; caller_epochs = 32'd0;
        tacc_ctl_valid = 1'b0; tacc_ctl_caller_id = 5'd0;
        tacc_ctl_priv = 1'b0; tacc_ctl_wdata = 64'd0;
        tile_ack_enable = 1'b1;
        ext_tile_rdata = 512'd0; ext_tile_ack = 1'b0;
        repeat (4) @(posedge clk);
        rst_n = 1;
        repeat (2) @(posedge clk);

        fd = $fopen("tile_fp_vectors.vec", "r");
        if (fd == 0) begin
            $display("FAIL: cannot open tile_fp_vectors.vec");
            $finish;
        end
        while (!$feof(fd)) begin
            line = 0;
            code = $fgets(line, fd);
            if (code > 0 && line[8*code-1 -: 8] != "#" &&
                $sscanf(line, "%s %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h",
                        name, v_ss, v_op, v_funct_byte, v_tmode, v_tctrl, v_gpr,
                        v_acc[0], v_acc[1], v_acc[2], v_acc[3],
                        v_src0, v_src1, v_dst, v_dst2, v_edst, v_edst2,
                        v_eacc[0], v_eacc[1], v_eacc[2], v_eacc[3],
                        v_etctrl, v_ez_valid, v_ez, v_check) == 25) begin
                vector_count = vector_count + 1;
                tile_mem[4] = v_src0;
                tile_mem[5] = v_src1;
                tile_mem[6] = v_dst;
                tile_mem[7] = v_dst2;
                csr_write(8'h14, {56'd0, v_tmode});
                csr_write(8'h15, {56'd0, v_tctrl});
                csr_write(8'h16, 64'h100);
                csr_write(8'h17, 64'h140);
                csr_write(8'h18, 64'h180);
                for (k = 0; k < 4; k = k + 1)
                    csr_write(8'h19 + k, v_acc[k]);
                dispatch(v_ss[1:0], v_op[1:0], v_funct_byte, v_gpr);
                csr_read(8'h15, tctrl_now);

                ok = 1'b1;
                if (v_check[0] && tile_mem[6] !== v_edst) begin
                    ok = 1'b0;
                    $display("  FAIL %0s: dst got %h expected %h",
                             name, tile_mem[6], v_edst);
                end
                if (v_check[1] && tile_mem[7] !== v_edst2) begin
                    ok = 1'b0;
                    $display("  FAIL %0s: dst2 got %h expected %h",
                             name, tile_mem[7], v_edst2);
                end
                for (k = 0; k < 4; k = k + 1)
                    if (v_check[2 + k] &&
                        legacy_acc_state[k*64 +: 64] !== v_eacc[k]) begin
                        ok = 1'b0;
                        $display("  FAIL %0s: acc%0d got %h expected %h",
                                 name, k, legacy_acc_state[k*64 +: 64],
                                 v_eacc[k]);
                    end
                if (v_check[6] && tctrl_now[7:0] !== v_etctrl) begin
                    ok = 1'b0;
                    $display("  FAIL %0s: tctrl got %h expected %h",
                             name, tctrl_now[7:0], v_etctrl);
                end
                if (v_check[7] &&
                    (seen_z_valid !== v_ez_valid[0] ||
                     (v_ez_valid[0] && seen_z !== v_ez[0]))) begin
                    ok = 1'b0;
                    $display("  FAIL %0s: Z update got %b/%b expected %b/%b",
                             name, seen_z_valid, seen_z,
                             v_ez_valid[0], v_ez[0]);
                end
                if (ok) pass_cnt = pass_cnt + 1;
                else    fail_cnt = fail_cnt + 1;
            end else if (code > 0 && line[8*code-1 -: 8] == "#") begin
                if ($sscanf(line, "# count %d", expected_count) != 1)
                    ;
            end
        end
        $fclose(fd);

        if (expected_count != vector_count) begin
            $display("FAIL: read %0d vectors, file declares %0d",
                     vector_count, expected_count);
            fail_cnt = fail_cnt + 1;
        end
        $display("");
        $display("tb_tile_fp: %0d vectors, %0d passed, %0d failed",
                 vector_count, pass_cnt, fail_cnt);
        if (fail_cnt == 0)
            $display("ALL TILE FP VECTORS PASSED");
        $finish;
    end
endmodule
