"""Machine-independent constants for the MegaPad block-storage ABI."""

from __future__ import annotations


SECTOR_SIZE = 512

STORAGE_CMD_READ = 0x01
STORAGE_CMD_WRITE = 0x02
STORAGE_CMD_STATUS = 0x03
STORAGE_CMD_RESET = 0x04
STORAGE_CMD_FLUSH = 0xFF

STORAGE_STATUS_BUSY = 0x01
STORAGE_STATUS_ERROR = 0x02
STORAGE_STATUS_REJECTED = 0x04
STORAGE_STATUS_RESULT_VALID = 0x08
STORAGE_STATUS_MEDIA_CHANGED = 0x10
STORAGE_STATUS_WRITE_PROTECTED = 0x20
STORAGE_STATUS_PRESENT = 0x80

STORAGE_RESULT_PARTIAL = 0x80
STORAGE_RESULT_OK = 0x00
STORAGE_RESULT_NO_MEDIA = 0x01
STORAGE_RESULT_UNSUPPORTED = 0x02
STORAGE_RESULT_INVALID_COUNT = 0x03
STORAGE_RESULT_LBA_RANGE = 0x04
STORAGE_RESULT_ADDRESS_OVERFLOW = 0x05
STORAGE_RESULT_DMA_INVALID = 0x06
STORAGE_RESULT_DMA_FAILURE = 0x07
STORAGE_RESULT_WRITE_PROTECTED = 0x08
STORAGE_RESULT_MEDIA_FAILURE = 0x09
STORAGE_RESULT_TIMEOUT = 0x0A
STORAGE_RESULT_MEDIA_REMOVED = 0x0B
STORAGE_RESULT_RESET_ABORTED = 0x0C
STORAGE_RESULT_FLUSH_FAILURE = 0x0D
STORAGE_RESULT_INTERNAL = 0x0E

STORAGE_CAP_READ = 0x01
STORAGE_CAP_WRITE = 0x02
STORAGE_CAP_FLUSH = 0x04
STORAGE_CAP_PRECISE_RESULT = 0x08
STORAGE_CAP_COMPLETION = 0x10
STORAGE_CAP_MEDIA_GEN = 0x20
STORAGE_CAP_GEN_GUARD = 0x40
STORAGE_CAPS = (
    STORAGE_CAP_READ
    | STORAGE_CAP_WRITE
    | STORAGE_CAP_FLUSH
    | STORAGE_CAP_PRECISE_RESULT
    | STORAGE_CAP_COMPLETION
    | STORAGE_CAP_MEDIA_GEN
    | STORAGE_CAP_GEN_GUARD
)


__all__ = [
    "SECTOR_SIZE",
    "STORAGE_CAPS",
    "STORAGE_CAP_COMPLETION",
    "STORAGE_CAP_FLUSH",
    "STORAGE_CAP_GEN_GUARD",
    "STORAGE_CAP_MEDIA_GEN",
    "STORAGE_CAP_PRECISE_RESULT",
    "STORAGE_CAP_READ",
    "STORAGE_CAP_WRITE",
    "STORAGE_CMD_FLUSH",
    "STORAGE_CMD_READ",
    "STORAGE_CMD_RESET",
    "STORAGE_CMD_STATUS",
    "STORAGE_CMD_WRITE",
    "STORAGE_RESULT_ADDRESS_OVERFLOW",
    "STORAGE_RESULT_DMA_FAILURE",
    "STORAGE_RESULT_DMA_INVALID",
    "STORAGE_RESULT_FLUSH_FAILURE",
    "STORAGE_RESULT_INTERNAL",
    "STORAGE_RESULT_INVALID_COUNT",
    "STORAGE_RESULT_LBA_RANGE",
    "STORAGE_RESULT_MEDIA_FAILURE",
    "STORAGE_RESULT_MEDIA_REMOVED",
    "STORAGE_RESULT_NO_MEDIA",
    "STORAGE_RESULT_OK",
    "STORAGE_RESULT_PARTIAL",
    "STORAGE_RESULT_RESET_ABORTED",
    "STORAGE_RESULT_TIMEOUT",
    "STORAGE_RESULT_UNSUPPORTED",
    "STORAGE_RESULT_WRITE_PROTECTED",
    "STORAGE_STATUS_BUSY",
    "STORAGE_STATUS_ERROR",
    "STORAGE_STATUS_MEDIA_CHANGED",
    "STORAGE_STATUS_PRESENT",
    "STORAGE_STATUS_REJECTED",
    "STORAGE_STATUS_RESULT_VALID",
    "STORAGE_STATUS_WRITE_PROTECTED",
]
